### ISSUE TITLE
POST /containers/{id}/start (ownership check)

### ISSUE THREAD

**Issue by alobaidan** [buildkite/sockguard#49]
Hi there,

Is it possible to make this command "POST /containers/{id}/start"  available just for a particular users ?

for example I have many users and Alice one of these users could I add Alice in this command to make Alice able to start container while others no. "POST /Alice/containers/{id}/start"

if yes could you send me how please ?
Best,
Ibrahim

**Comment by lox** [comment]
:wave: Could you explain a bit more about why you want that?

**Comment by alobaidan** [comment]
Hi ,

I would like to make just a particular users to can start container.

For example I have Bob and Alice users.

I would like just Alice who can start container while Bob can’t.

I have created an authorisation plugin but I couldn’t make the authorisation plugin look to the user.

**Comment by alobaidan** [comment]
Ok, Many thanks lox
