### ISSUE TITLE
/usr/bin/sockguard: line 1: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by ay-b** [buildkite/sockguard#54]
Hi.
I was trying to use this promising package, but fell into an error
```
line 1: syntax error near unexpected token \`newline\'
line 1: \`!<arch>\'
```
I was building it with
```
cd /tmp
git clone https://github.com/buildkite/sockguard.git
docker-compose up -d
sudo docker cp sockguard_sockguard_1:/sockguard /usr/sbin/
docker-compose kill
```

Project was build in OSx, Centos, and Ubuntu resulting the same error on binary launch. 

Any advice would be appreciated.

**Comment by CpuID** [comment]
@ay-b can you `cat` the file...? feels like it might be plaintext?
