### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by CpuID** [buildkite/sockguard#7]
Hey @lox,

A few questions:

- how would you feel about using https://github.com/urfave/cli (or something similar) for CLI arg parsing, to allow for args and/or env vars to be used, instead of `flag`?
- would test coverage be of interest to you?

**Comment by lox** [comment]
Yup, I'd be ok with `urfave/cli` or https://github.com/alecthomas/kingpin. The latter is probably better out of the box these days.

**Comment by lox** [comment]
I've been planning to add some tests, this was a weekend prototype that ended up not needing much follow up till now!

**Comment by CpuID** [comment]
> Yup, I'd be ok with urfave/cli or https://github.com/alecthomas/kingpin. The latter is probably better out of the box these days.

kingpin looks reasonably good, does it mandate using `=` between flag names and values? Or does it take both `--flag value` + `--flag=value` syntax? I tend to default to `--flag value` when typing something these days, obviously depends on the end user.

**Comment by CpuID** [comment]
> I've been planning to add some tests, this was a weekend prototype that ended up not needing much follow up till now!

fair call :) as they always start. I'd be open to contributing some of my mock work potentially from dockerd-ci-proxy here... time permitting.

**Comment by lox** [comment]
> kingpin looks reasonably good, does it mandate using = between flag names and values? Or does it take both --flag value + --flag=value syntax? I tend to default to --flag value when typing something these days, obviously depends on the end user.

Nope, either works I believe.

**Comment by CpuID** [comment]
> Nope, either works I believe.

nice, sounds good then :)

**Comment by lox** [comment]
Gonna close this one for now @CpuID!

**Comment by CpuID** [comment]
:+1:
