### ISSUE TITLE
Dealing with the <enter> required to close a TTY shell + 500 on "docker exec"

### ISSUE THREAD

**Issue by CpuID** [buildkite/sockguard#8]
If you run something like:

```
DOCKER_HOST=unix://./sockguard.sock docker run -it --rm alpine:3.8 sh -c "sleep 1 && echo 'asdf'"
```

The container runs and exits gracefully, and should even return `asdf`. But it will hang instead of taking you back to the out-of-band shell/terminal that executed `docker run` in the first place.

Interestingly, if you omit `-it`, this falls back to a shell without issue. (non-TTY)

------------------

In addition, if you try something like:

```
$ DOCKER_HOST=unix://./sockguard.sock docker run -d alpine:3.8 sleep 1000
6f5faacecdb1e824a45f5f404e7eadc58c6a097464d7ce23fa2087e9d682be2e
$ $ DOCKER_HOST=unix://./sockguard.sock docker exec -it condescending_noyce sh
unable to upgrade to tcp, received 500
```

The proxy is unable to handle the `101 UPGRADED` HTTP response gracefully.

See https://github.com/CpuID/dockerd-ci-proxy/issues/3 for some context - I hit a similar issue, unsolved :)

In theory, you may or may not run into this when using sockguard exclusively in CI (`docker run -it` is less plausible, `docker exec` without `-it` maybe?).

**Comment by lox** [comment]
Urgh, I thought I had solved this one. I remember this happening with early versions of docker too.

**Comment by CpuID** [comment]
@lox any theories into this...? just got bitten on our CI server, running `command:` lines in `docker-compose.yml` files to output some stuff to stdout, and it hangs :(

I know I definitely hit my head against a wall when I tried to debug it originally... but it feels like the way HTTP responses are sent over the socket + buffering of headers and/or bodies?

**Comment by lox** [comment]
I'm going to try the new tracing stuff in golang head to see if I can figure out where it's getting blocked.  I swear I had this fixed. Would also be great to add some tests to catch this.

**Comment by CpuID** [comment]
> I'm going to try the new tracing stuff in golang head to see if I can figure out where it's getting blocked. I swear I had this fixed. Would also be great to add some tests to catch this.

+100

**Comment by CpuID** [comment]
[mitm-docker.zip](https://github.com/buildkite/sockguard/files/2313113/mitm-docker.zip)
[sockguard-cli-side.zip](https://github.com/buildkite/sockguard/files/2313114/sockguard-cli-side.zip)
[sockguard-daemon-side.zip](https://github.com/buildkite/sockguard/files/2313115/sockguard-daemon-side.zip)

3 PCAPs attached (zipped):

`mitm-docker.pcap` - socat unix socket -> TCP 15001, then another socat TCP 15001 -> docker.sock. using `DOCKER_HOST=unix:/mitm.sock docker run -it --rm alpine:3.8 sh`, <count to 5~ while looking at an open shell>, `exit<enter>`, returns to the host shell

`sockguard-cli-side.pcap` (docker CLI to sockguard, guarded side) + `sockguard-daemon-side.pcap` (sockguard to docker, unguarded side) - same approach as above, `DOCKER_HOST=unix:/cli-side.sock docker run -it --rm alpine:3.8 sh`, <count to 5~ while looking at an open shell>, `exit<enter>`, <count to 5~ looking at a hung shell after hitting exit, no prompt>, ctrl+c, returns to the host shell

I'll start analysing shortly (have to leave my desk for a bit)

**Comment by CpuID** [comment]
FYI - I've hit this maybe 3~ times this week, but in the end worked around it in a hacky way by not doing interactive shells to any containers (shouldn't be needed in CI, most of the time a `docker logs -f` or `docker-compose logs -f` + `docker wait containername` -> get exit code yields an equivalent outcome)

**Comment by lox** [comment]
I'd love to fix this one, been trying to find time to investigate too.
